- name: Ensure rsync is installed
  apt: name=rsync state=present

- name: Ensure backupro user exists
  user: name=backupro

- name: Create ssh directory
  file: name=/home/backupro/.ssh state=directory owner=backupro group=backupro

# This doesn't work in ansible >2.0, as it uses agent forwarding (security risk!)
#- name: Copy ssh key of backup pulling host
#  synchronize:
#    src: /test
#    dest: /test
#  delegate_to: n54l

- name: Fetch ssh key from backup pulling host
  fetch: src=/home/backuppuller/.ssh/id_rsa.pub dest=tmp-rsnapshot-ssh-key fail_on_missing=yes flat=yes
  delegate_to: "{{ rsnapshot_backup_host }}"
  changed_when: False
  when: testing is not defined

- name: Create ssh key for testing
  copy:
    content: "ssh-rsa AAAA== test@example.org"
    dest: ./tmp-rsnapshot-ssh-key
  delegate_to: 127.0.0.1
  changed_when: False
  when: testing is defined

- name: Add key to authorized_keys
  authorized_key:
    user: backupro
    key: "{{ lookup('file', 'tmp-rsnapshot-ssh-key') }}"
    key_options: 'command="/home/backupro/.ssh/command-wrapper.sh",no-agent-forwarding,no-port-forwarding,no-pty,no-user-rc,no-X11-forwarding'

- name: Fetch ssh hostkey
  fetch: src=/etc/ssh/ssh_host_ecdsa_key.pub dest=tmp-rsnapshot-host-key fail_on_missing=yes flat=yes
  changed_when: False

- name: Install hostkey on backup pulling host
  known_hosts:
    path: /home/backuppuller/.ssh/known_hosts
    name: "{{ ansible_host }}"
    key: "{{ ansible_host + ',' + ansible_fqdn + ',' + ansible_all_ipv4_addresses|union(ansible_all_ipv6_addresses)|join(',') + ' ' + lookup('file', 'tmp-rsnapshot-host-key') }}"
  delegate_to: "{{ item }}"
  with_items:
    - "{{ rsnapshot_backup_host }}"
  when: testing is not defined

- name: Remove temporary files from local host
  sudo: no
  local_action: file state=absent path={{ item }}
  with_items:
    - tmp-rsnapshot-host-key
    - tmp-rsnapshot-ssh-key
  changed_when: False

- name: Install rrsync
  template: src=rrsync dest=/usr/local/bin/rrsync mode=755 owner=root group=root

- name: Make sure /var/log/rrsync.log is created with correct permissions
  copy: content="" dest=/var/log/rrsync.log mode=600 owner=root group=root force=no

- name: Add sudoers config
  blockinfile:
    dest: /etc/sudoers
    block: |
      backupro ALL=NOPASSWD: /usr/local/bin/rrsync
      backupro ALL=NOPASSWD: /etc/rsnapshot/backup-scripts/
      Defaults!/usr/local/bin/rrsync env_keep+="SSH_ORIGINAL_COMMAND SSH_CONNECTION"
    marker: "# {mark} rsnapshot-remote-host sudoers settings"
    validate: 'visudo -cf %s'

- name: Install ssh wrapper script
  template: src=command-wrapper.sh dest=/home/backupro/.ssh/command-wrapper.sh owner=root group=root mode=655

- name: Install backup-scripts
  copy: src=backup-scripts dest=/etc/rsnapshot/ owner=root group=root mode=755
